name: hostel_outpass_app
description: "A new Flutter project for hostel outpass management."
publish_to: 'none' # This prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.3          # Correct latest stable version for Firebase Auth
  firebase_core: ^3.8.0          # Correct latest stable version for Firebase Core
  cloud_firestore: ^5.5.0        # Latest stable version for Firestore
  fluttertoast: ^8.2.1           # For showing toast notifications
  qr_flutter: ^4.0.0             # For generating QR codes
  provider: ^6.1.2               # Correct latest stable version for Provider

  logging: ^1.0.1

  qr_code_scanner: ^0.4.0
  
  async: 2.11.0
  
  characters: 1.3.0
  collection: 1.18.0

  

dev_dependencies:
  #flutter_test:
   # sdk: flutter
  flutter_lints: ^5.0.0          # Latest stable version for linting

flutter:
  uses-material-design: true

  # Uncomment and modify these lines if you plan to include assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Uncomment and modify this section if you use custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
